services:
    blog:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: blog
        restart: unless-stopped
        env_file: .env
        ports:
            - "4321:4321"
        environment:
            - HOST=0.0.0.0
            - PORT=4321
            - NODE_ENV=production
