collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Body", name: "body", widget: "richtext" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Author", name: "author", widget: "hidden", default: "nerometa" }
      - { label: "Slug", name: "slug", widget: "text" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
  - media_folder: "public/images" # Location where files will be stored in the repo
  - public_folder: "public/images" # The src attribute for uploaded media
